DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

TRAINER:
  BIOMEDCOOP:
    CTX_INIT: "a dermoscopy image of a"
    SCCM_LAMBDA: 5.0
    KDSP_LAMBDA: 20.0
    TAU: 1.75
    N_PROMPTS: 50

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.0025
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

DATASET:
  ROOT: /storage/projects3/e19-fyp-out-of-domain-gen-in-cv/Derm7pt/release_v0
  NAME: Derm7pt
  NUM_SHOTS: 100
